"""relate users to books

Revision ID: 1cbd3fb84dc2
Revises: c6dd474f4766
Create Date: 2024-10-23 10:01:57.307421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1cbd3fb84dc2'
down_revision: Union[str, None] = 'c6dd474f4766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('published', sqlmodel.sql.sqltypes.AutoString(), server_default='TRUE', nullable=False))
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_books_user_uid'), 'books', ['user_uid'], unique=False)
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_user_uid'), table_name='books')
    op.drop_column('books', 'user_uid')
    op.drop_column('books', 'published')
    # ### end Alembic commands ###
