"""add review table

Revision ID: c2ee8fa8fef7
Revises: 1cbd3fb84dc2
Create Date: 2024-10-28 13:50:50.684244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2ee8fa8fef7'
down_revision: Union[str, None] = '1cbd3fb84dc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('review_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=True),
    sa.Column('book_uid', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_reviews_book_uid'), 'reviews', ['book_uid'], unique=False)
    op.create_index(op.f('ix_reviews_uid'), 'reviews', ['uid'], unique=True)
    op.create_index(op.f('ix_reviews_user_uid'), 'reviews', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_uid'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_uid'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_book_uid'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
